#https://hub.docker.com/r/mitmproxy/mitmproxy

#docker run --rm -it [-v ~/.mitmproxy:/home/mitmproxy/.mitmproxy] -p 8080:8080 mitmproxy/mitmproxy

#docker run --rm -it -p 8080:8080 mitmproxy/mitmproxy mitmdump

#docker run --rm -it -p 8080:8080 -p 127.0.0.1:8081:8081 mitmproxy/mitmproxy mitmweb --web-iface 0.0.0.0

version: '3.7'
services:

  proxy:
    image: mitmproxy/mitmproxy:4.0.4
    ports:
    - "8080:8080/tcp"
    extra_hosts:
    - "chat-dev.metamodel.ru:192.168.0.140"
    volumes:
    - "./config.yml:/home/mitmproxy/.mitmproxy/config.yaml:rw"
    stdin_open: true
    tty: true

  dump:
    image: mitmproxy/mitmproxy:4.0.4
    ports:
    - "8080:8080/tcp"
    extra_hosts:
    - "chat-dev.metamodel.ru:192.168.0.140"
    volumes:
    - "./config.yml:/home/mitmproxy/.mitmproxy/config.yaml:rw"
    command: mitmdump

  web:
    image: mitmproxy/mitmproxy:4.0.4
    ports:
    - "8080:8080/tcp"
    - "8081:8081/tcp"
    extra_hosts:
    - "chat-dev.metamodel.ru:192.168.0.140"
    volumes:
    - "./config.yml:/home/mitmproxy/.mitmproxy/config.yaml:rw"
    command: mitmweb --web-iface 0.0.0.0
  